# Generated by Django 4.0.1 on 2022-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
