# Generated by Django 4.0.1 on 2022-01-24 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_posted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
