# Generated by Django 4.0.1 on 2022-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_video_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
